HrPtoManagement.Web/Controllers/PtoTypesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HrPtoManagement.Web.Data;
using AutoMapper;
using HrPtoManagement.Web.Models;
using HrPtoManagement.Web.Interfaces;
using Microsoft.AspNetCore.Authorization;
using HrPtoManagement.Web.Constants;

namespace HrPtoManagement.Web.Controllers
{
    [Authorize(Roles = Roles.Administrator)]
    public class PtoTypesController : Controller
    {
        private readonly IPtoTypeRepository ptoTypeRepository;
        private readonly IMapper mapper;

        public PtoTypesController(IPtoTypeRepository ptoTypeRepository, IMapper mapper)
        {
            this.ptoTypeRepository = ptoTypeRepository;
            this.mapper = mapper;
        }

        // GET: PtoTypes
        public async Task<IActionResult> Index()
        {
            var ptoTypes = mapper.Map<List<PtoTypeViewModel>>(await ptoTypeRepository.GetAllAsync());
            return View(ptoTypes);
        }

        // GET: PtoTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var ptoType = await ptoTypeRepository.GetAsync(id);
            if (ptoType == null)
            {
                return NotFound();
            }

            var ptoTypeViewModel = mapper.Map<PtoTypeViewModel>(ptoType);
            return View(ptoTypeViewModel);
        }

        // GET: PtoTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PtoTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PtoTypeViewModel ptoTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                var ptoType = mapper.Map<PtoType>(ptoTypeViewModel);
                await ptoTypeRepository.AddAsync(ptoType);
                return RedirectToAction(nameof(Index));
            }
            return View(ptoTypeViewModel);
        }

        // GET: PtoTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var ptoType = await ptoTypeRepository.GetAsync(id);
            if (ptoType == null)
            {
                return NotFound();
            }

            var ptoTypeViewModel = mapper.Map<PtoTypeViewModel>(ptoType);
            return View(ptoTypeViewModel);
        }

        // POST: PtoTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PtoTypeViewModel ptoTypeViewModel)
        {
            if (id != ptoTypeViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var ptoType = mapper.Map<PtoType>(ptoTypeViewModel);
                    await ptoTypeRepository.UpdateAsync(ptoType);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await ptoTypeRepository.Exists(ptoTypeViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ptoTypeViewModel);
        }

        // POST: PtoTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await ptoTypeRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

HrPtoManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HrPtoManagement.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HrPtoManagement.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR PTO Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="" asp-action="">Apply For PTO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="" asp-action="">My PTO</a>
                        </li>
                        @if (User.IsInRole(Roles.Administrator))
                        {
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                PTO Management
                              </a>
                              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="PtoTypes" asp-action="Index">PTO Types</a></li>
                                <li><a class="dropdown-item" href="#">PTO Allocations</a></li>
                                <li><a class="dropdown-item" href="#">PTO Requests</a></li>
                                <li><a class="dropdown-item" href="#">Employee Management</a></li>
                              </ul>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - HR PTO Management Tool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap5.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>